# Generated by Django 4.1.1 on 2022-10-13 16:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusuario',
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
